source 'https://rubygems.org'

gem 'active_model_serializers', '0.8.3'
gem 'rails', '4.2.0'
gem 'rails-api'
gem 'rack-rewrite'
gem 'pg'
gem 'pry-rails'

group :production do
  gem 'rails_12factor'
end

group :development do
  gem 'spring'
  gem 'rack-cors', require: 'rack/cors'
end
